#!/bin/bash
# GnuNae Sandbox Container Entrypoint
#
# This script initializes the sandbox environment:
# 1. Starts Xvfb (virtual framebuffer)
# 2. Starts VNC server if enabled
# 3. Starts noVNC web proxy if enabled
# 4. Launches Chromium with CDP enabled (headless mode only)
# 5. Starts the API server

set -e

# Configuration from environment
CDP_PORT=${CDP_PORT:-9222}
API_PORT=${API_PORT:-3000}
VNC_ENABLED=${VNC_ENABLED:-false}
VNC_PORT=${VNC_PORT:-5900}
NOVNC_PORT=${NOVNC_PORT:-6080}
VNC_RESOLUTION=${VNC_RESOLUTION:-1280x720}
VNC_DEPTH=${VNC_DEPTH:-24}
VNC_PASSWORD=${VNC_PASSWORD:-sandbox}

# Browser mode configuration
# - 'headless': Container runs its own Chromium (default)
# - 'electron-cdp': Connect to Electron's BrowserView via CDP
# - 'external-cdp': Connect to external browser via CDP
BROWSER_MODE=${BROWSER_MODE:-headless}
EXTERNAL_CDP_ENDPOINT=${EXTERNAL_CDP_ENDPOINT:-}
START_BROWSER=${START_BROWSER:-true}

LOG_DIR="/var/log/sandbox"

echo "[Sandbox] Starting GnuNae Sandbox Container..."
echo "[Sandbox] Browser Mode: $BROWSER_MODE"
echo "[Sandbox] API Port: $API_PORT"
if [ "$BROWSER_MODE" = "headless" ]; then
    echo "[Sandbox] CDP Port: $CDP_PORT (internal browser)"
else
    echo "[Sandbox] External CDP: $EXTERNAL_CDP_ENDPOINT"
fi
echo "[Sandbox] VNC Enabled: $VNC_ENABLED"

# ========= Generate Codex config with Playwright MCP =========
# This ensures Codex inside the container has access to Playwright MCP tools
CODEX_CONFIG_DIR="/home/sandbox/.codex"
CODEX_CONFIG_FILE="$CODEX_CONFIG_DIR/config.toml"

mkdir -p "$CODEX_CONFIG_DIR"

# Determine CDP endpoint for Playwright MCP
if [ "$BROWSER_MODE" = "headless" ]; then
    PLAYWRIGHT_CDP="http://127.0.0.1:$CDP_PORT"
else
    # For external CDP mode, we need a socat proxy to bypass Chrome's Host header validation
    # Chrome rejects requests where Host header is not localhost/127.0.0.1/IP address
    # host.docker.internal in Host header causes HTTP 500
    
    # Extract port from external endpoint (e.g., http://host.docker.internal:9223 -> 9223)
    EXTERNAL_PORT=$(echo "$EXTERNAL_CDP_ENDPOINT" | grep -oE ':[0-9]+' | tail -1 | tr -d ':')
    EXTERNAL_PORT=${EXTERNAL_PORT:-9223}
    
    # Resolve host.docker.internal to its actual IP address
    # Prefer IPv4 over IPv6 because IPv6 URLs need special bracket formatting
    EXTERNAL_HOST_IP=$(getent ahostsv4 host.docker.internal 2>/dev/null | awk '{print $1}' | head -1)
    
    # Fallback to any IP if IPv4 not found
    if [ -z "$EXTERNAL_HOST_IP" ]; then
        EXTERNAL_HOST_IP=$(getent hosts host.docker.internal | awk '{print $1}' | head -1)
        # Check if it's IPv6 (contains colons) and add brackets if needed
        if [[ "$EXTERNAL_HOST_IP" == *:* ]]; then
            EXTERNAL_HOST_IP="[${EXTERNAL_HOST_IP}]"
            echo "[Sandbox] Using IPv6 address with brackets: $EXTERNAL_HOST_IP"
        fi
    fi
    
    if [ -n "$EXTERNAL_HOST_IP" ]; then
        echo "[Sandbox] Resolved host.docker.internal to: $EXTERNAL_HOST_IP"
        # Use the resolved IP instead of hostname to bypass Host header validation
        PLAYWRIGHT_CDP="http://${EXTERNAL_HOST_IP}:${EXTERNAL_PORT}"
    else
        echo "[Sandbox] WARNING: Could not resolve host.docker.internal, using original endpoint"
        PLAYWRIGHT_CDP="$EXTERNAL_CDP_ENDPOINT"
    fi
fi

echo "[Sandbox] Generating Codex config with Playwright MCP..."
echo "[Sandbox] Playwright CDP endpoint: $PLAYWRIGHT_CDP"

cat > "$CODEX_CONFIG_FILE" << EOF
# GnuNae Sandbox Codex Configuration
# Auto-generated by entrypoint.sh

[mcp_servers]

[mcp_servers.playwright]
type = "stdio"
command = "npx"
args = ["@playwright/mcp@latest", "--cdp-endpoint", "$PLAYWRIGHT_CDP"]
EOF

echo "[Sandbox] Codex config generated at $CODEX_CONFIG_FILE"
# ========= End Codex config generation =========

# Function to cleanup on exit
cleanup() {
    echo "[Sandbox] Shutting down..."
    
    # Kill child processes
    pkill -f "Xvfb" 2>/dev/null || true
    pkill -f "x11vnc" 2>/dev/null || true
    pkill -f "websockify" 2>/dev/null || true
    pkill -f "chromium" 2>/dev/null || true
    pkill -f "fluxbox" 2>/dev/null || true
    
    echo "[Sandbox] Shutdown complete"
    exit 0
}

trap cleanup SIGTERM SIGINT

# Start Xvfb (virtual framebuffer)
echo "[Sandbox] Starting Xvfb virtual display..."
Xvfb :99 -screen 0 ${VNC_RESOLUTION}x${VNC_DEPTH} -ac +extension GLX +render -noreset > "${LOG_DIR}/xvfb.log" 2>&1 &
XVFB_PID=$!

# Wait for Xvfb to be ready
sleep 2
if ! kill -0 $XVFB_PID 2>/dev/null; then
    echo "[Sandbox] ERROR: Xvfb failed to start"
    cat "${LOG_DIR}/xvfb.log"
    exit 1
fi
echo "[Sandbox] Xvfb started (PID: $XVFB_PID)"

# Start a simple window manager (optional, helps with some apps)
fluxbox > "${LOG_DIR}/fluxbox.log" 2>&1 &
FLUXBOX_PID=$!
echo "[Sandbox] Fluxbox window manager started (PID: $FLUXBOX_PID)"

# Start VNC if enabled
if [ "$VNC_ENABLED" = "true" ]; then
    echo "[Sandbox] Starting VNC server on port $VNC_PORT..."
    
    # Create VNC password file
    mkdir -p ~/.vnc
    x11vnc -storepasswd "$VNC_PASSWORD" ~/.vnc/passwd
    
    # Start x11vnc
    x11vnc -display :99 \
        -rfbport $VNC_PORT \
        -rfbauth ~/.vnc/passwd \
        -forever \
        -shared \
        -noxdamage \
        -noxfixes \
        -xkb \
        > "${LOG_DIR}/x11vnc.log" 2>&1 &
    X11VNC_PID=$!
    
    sleep 2
    if kill -0 $X11VNC_PID 2>/dev/null; then
        echo "[Sandbox] VNC server started (PID: $X11VNC_PID)"
        
        # Start noVNC websocket proxy
        echo "[Sandbox] Starting noVNC on port $NOVNC_PORT..."
        websockify --web=/usr/share/novnc/ $NOVNC_PORT localhost:$VNC_PORT > "${LOG_DIR}/novnc.log" 2>&1 &
        NOVNC_PID=$!
        echo "[Sandbox] noVNC started (PID: $NOVNC_PID)"
        echo "[Sandbox] VNC web interface available at: http://localhost:$NOVNC_PORT/vnc.html"
    else
        echo "[Sandbox] WARNING: VNC server failed to start"
        cat "${LOG_DIR}/x11vnc.log"
    fi
fi

# Find Chromium path (varies by installation)
CHROMIUM_BIN=""
for chrome_path in \
    "/ms-playwright/chromium-*/chrome-linux/chrome" \
    "/usr/bin/chromium" \
    "/usr/bin/chromium-browser" \
    "/usr/bin/google-chrome"
do
    CHROME_PATH=$(ls $chrome_path 2>/dev/null | head -1)
    if [ -n "$CHROME_PATH" ]; then
        CHROMIUM_BIN="$CHROME_PATH"
        break
    fi
done

if [ -z "$CHROMIUM_BIN" ]; then
    echo "[Sandbox] WARNING: Chromium not found, CDP may not work properly"
else
    echo "[Sandbox] Found Chromium at: $CHROMIUM_BIN"
fi

# Launch Chromium with CDP enabled (if found and not using Playwright's browser)
# Note: Playwright MCP will manage its own browser, but we can start one for direct CDP access
if [ -n "$CHROMIUM_BIN" ] && [ "${START_BROWSER:-false}" = "true" ]; then
    echo "[Sandbox] Starting Chromium with CDP on port $CDP_PORT..."
    "$CHROMIUM_BIN" \
        --remote-debugging-port=$CDP_PORT \
        --remote-debugging-address=0.0.0.0 \
        --no-first-run \
        --no-default-browser-check \
        --disable-gpu \
        --disable-software-rasterizer \
        --disable-dev-shm-usage \
        --no-sandbox \
        --disable-setuid-sandbox \
        --window-size=1280,720 \
        about:blank \
        > "${LOG_DIR}/chromium.log" 2>&1 &
    CHROMIUM_PID=$!
    echo "[Sandbox] Chromium started (PID: $CHROMIUM_PID)"
fi

# Start the API server
echo "[Sandbox] Starting API server on port $API_PORT..."
cd /app

# Check if compiled JS exists, otherwise use ts-node
if [ -f "api-server.js" ]; then
    node api-server.js &
else
    npx ts-node api-server.ts &
fi
API_PID=$!

# Wait for API server to be ready
sleep 3
if kill -0 $API_PID 2>/dev/null; then
    echo "[Sandbox] API server started (PID: $API_PID)"
else
    echo "[Sandbox] ERROR: API server failed to start"
    exit 1
fi

echo "[Sandbox] ================================================"
echo "[Sandbox] Sandbox is ready!"
echo "[Sandbox] Browser Mode: $BROWSER_MODE"
if [ "$BROWSER_MODE" = "headless" ]; then
    echo "[Sandbox] CDP endpoint: http://localhost:$CDP_PORT"
else
    echo "[Sandbox] External CDP: $EXTERNAL_CDP_ENDPOINT"
fi
echo "[Sandbox] API endpoint: http://localhost:$API_PORT"
if [ "$VNC_ENABLED" = "true" ]; then
    echo "[Sandbox] VNC: vnc://localhost:$VNC_PORT (password: $VNC_PASSWORD)"
    echo "[Sandbox] noVNC: http://localhost:$NOVNC_PORT/vnc.html"
fi
echo "[Sandbox] ================================================"

# Keep the container running and wait for signals
wait $API_PID
